services:
  baget:
    image: loicsharma/baget
    environment:
    - ApiKey=acd0b30512ac4fa39f62eb7a61fcf56c
    ports:
    - 5555:80

  # Username: registryuser
  # Password: registrypassword
  registry:
    image: registry:2
    ports:
    - 5000:5000
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Bake test registry"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    volumes:
    - ./Services/Registry:/auth

  chart-museum:
    image: ghcr.io/helm/chartmuseum:v0.15.0
    ports:
    - 5556:8080
    environment:
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /tmp
