<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackageId>awesome-cli-tool</PackageId>
    <TargetFramework>net6.0</TargetFramework>
    <IsTool>true</IsTool>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>magic-command</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
