<Project>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />

    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) Rasmus Mikkelsen 2021-2026</Copyright>
    <NoWarn>1701;1702;1705;1591;NU1901</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\..\..\icon.png" Pack="true" PackagePath="\"/>
    <None Include="$(MSBuildProjectDirectory)\..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
