<Project>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />

    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) Rasmus Mikkelsen 2021-2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\..\..\icon.png" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildProjectDirectory)\..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
