name: pull-requests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      baget:
        image: loicsharma/baget
        env:
          ApiKey=acd0b30512ac4fa39f62eb7a61fcf56c
        ports:
        - 5555:80

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --include-source --include-symbols --verbosity normal

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          **/*.nupkg
          **/*.snupkg
          
