name: pull-requests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      
    - name: Start Docker services
      run: docker-compose up -d --force-recreate

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Go 1.17.2
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17.2'
    - name: Setup Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Create a CLI version of Bake to use
      run: dotnet publish -o bake-it Source/Bake

    - name: Run Bake
      run: bake-it/bake run --build-version 0.20.$GITHUB_RUN_NUMBER

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: "**/*.trx"
        if-no-files-found: error
