name: pull-requests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/pipeline.yaml
    with:
      version: 0.42.${{ github.run_number }}
