name: pull-requests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    services:
      baget:
        image: loicsharma/baget
        env:
          ApiKey: acd0b30512ac4fa39f62eb7a61fcf56c
        ports:
        - 5555:80

      registry:
        image: registry:2
        ports:
        - 5000:5000
        env:
          REGISTRY_AUTH: "htpasswd"
          REGISTRY_AUTH_HTPASSWD_REALM: "Bake test registry"
          REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
        volumes:
          - ./Services/Registry:/auth

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Publish Bake
      run: dotnet publish -o bake-it Source/Bake

    - name: Run Bake
      run: bake-it/Bake run --build-version 0.1.$GITHUB_RUN_NUMBER --print-plan=true
