name: release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}

    services:
      baget:
        image: loicsharma/baget
        env:
          ApiKey: acd0b30512ac4fa39f62eb7a61fcf56c
        ports:
        - 5555:80

    steps:
    - uses: actions/checkout@v2

    - name: Start Docker registry (delayed, as we need to mount the htpasswd from the checkout)
      run: |
        docker run \
          -d \
          -v ${{ github.workspace }}/Services/Registry:/auth:rw \
          -p 5000:5000 \
          -e "REGISTRY_AUTH=htpasswd" \
          -e "REGISTRY_AUTH_HTPASSWD_REALM=Bake test registry" \
          -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
          registry:2
      
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Go 1.17.2
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.2'
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create a CLI version of Bake to use
      run: dotnet publish -o bake-it Source/Bake

    - name: Run Bake
      run: bake-it/bake run --convention=Release --build-version 0.11.$GITHUB_RUN_NUMBER --destination="nuget>github,nuget,release>github"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: "**/*.trx"
        if-no-files-found: error
