name: release

on:
  push:
    branches: [ release ]

permissions:
  contents: write
  issues: read
  packages: write
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/pipeline.yaml
    with:
      version: 0.39.${{ github.run_number }}
      bake-convention: release
    secrets:
      nuget-apikey: ${{ secrets.NUGET_APIKEY }}
