name: release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      baget:
        image: loicsharma/baget
        env:
          ApiKey: acd0b30512ac4fa39f62eb7a61fcf56c
        ports:
        - 5555:80

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    - name: Publish Bake
      run: dotnet publish -o bake-it Source/Bake

    - name: Run Bake
      run: bake-it/Bake run --convention=Release --build-version 0.0.$GITHUB_RUN_NUMBER --destination=nuget>github
